# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    #gradle(task: "clean assembleRelease")
    #crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
    # собираем билд

        path = '../app/build.gradle'
        re = /versionCode\s+(\d+)/
        s = File.read(path)
        versionCode = s[re, 1].to_i
        s[re, 1] = (versionCode + 1).to_s
        f = File.new(path, 'w')
        f.write(s)
        f.close

        gradle(
          task: "clean assembleRelease",
          properties: {
            "android.injected.signing.store.file" => "/Users/user/dev/api/deploy/kalpa.keystore",
            "android.injected.signing.store.password" => "$4f3cvbz",
            "android.injected.signing.key.alias" => "kalpa",
            "android.injected.signing.key.password" => "$4f3cvbz",
          }
        )

        # публикуем в бета-канал (если закомментить (track: 'beta',) - то в продакшн)
        upload_to_play_store(
          # track: 'beta',
          skip_upload_metadata: false,
          skip_upload_images: true,
          skip_upload_screenshots: true,
          skip_upload_apk: false)
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
