export default {
  initialized: false,
  // menuAppShow: false,
  // borderRadius: 8,
  // pageMaxWidth: 900,
  // maxWidthMenu: 280,
  // actionOptions: null,
  // actionOpened: false,
  // actionKey: null,
  // height: 0,
  // offsetTop: 0,
  // iWantSound: false,
  // showDrawerLeft: false,
  // appShowMenu: false,
  // appShowMobileNavigation: false,
  // appFullscreen: false,
  // panelMaxWidth: 0,
  // wsShowMenu: true,
  // stores: {},
  // active: true,
  // // new
  // showMobileNavigation: true,
  // showDesktopNavigation: true,
  // showLeftDrawer: false,
  // showAuth: false,
  // isTyping: false,
  // contentNodes: null,
  // editorItem: null
  pageWidth: 700,
  pageWidthDefault: 700,
  mobileNavigationShow: true,
  mobileNavigationStyles: {},
  mobileMenuShow: false,
  desktopNavigationShow: true,
  desktopNavigationStyles: {},
  contentFigures: {},
  userTyping: false,
  nodeEditorItem: null,
  jointEditorItem: null,
}
