export default {
  initialized: false,
  menuAppShow: false,
  borderRadius: 8,
  maxWidthPage: 800,
  maxWidthMenu: 280,
  actionOptions: null,
  actionOpened: false,
  actionKey: null,
  height: 0,
  offsetTop: 0,
  iWantSound: false,
  showDrawerLeft: false,
  appShowMenu: false,
  appShowMobileNavigation: false,
  appFullscreen: false,
  panelMaxWidth: 0,
  wsShowMenu: true,
  stores: {},
  active: true,
  // new
  showMobileNavigation: true,
}
